MovieMaven/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieMaven.Models
{
    public class Actor
    {
        public string birthday { get; set; }
        public string known_for_department { get; set; }
        public object deathday { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public List<string> also_known_as { get; set; }
        public int gender { get; set; }
        public string biography { get; set; }
        public double popularity { get; set; }
        public string place_of_birth { get; set; }
        public string profile_path { get; set; }
        public bool adult { get; set; }
        public string imdb_id { get; set; }
        public object homepage { get; set; }
    }
}

MovieMaven/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieMaven.Pages
{
    public class AboutModel : PageModel
    {
        public List<string> posterURLs = new List<string>();
        public List<string> overviews = new List<string>();
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }

    }
}

MovieMaven/Pages/Actor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieMaven.MovieAPI;
using MovieMaven.Models;

namespace MovieMaven.Pages
{
    public class ActorModel : PageModel
    {
        public string biography;
        public string actorName;
        public string birthday;
        public int age;
        public string placeOfBirth;
        public string knownFor;
        public string homepage;
        public List<string> imageUrls = new List<string>();
        public List<string> movieImages = new List<string>();
        public bool backToHome = false;

        public async Task OnGet(string id)
        {
            await Fetch.GetActorDetails(id);
            await Fetch.GetActorImages(id);

            for(int i = 0; i < Program.profileSet.profiles.Count; i++)
            {
                imageUrls.Add(Program.profileSet.profiles[i].file_path);
            }

            await Fetch.GetRelatedMovies(id);

            for(int i = 0; i < Program.relatedSet.results.Count; i++)
            {
                movieImages.Add(Program.relatedSet.results[i].poster_path);
            }

            biography = Program.actor.biography;
            actorName = Program.actor.name;
            birthday = Program.actor.birthday;
            // calculate age
            if (Program.actor.birthday != null) {
                age = DateTime.Now.Year - Convert.ToInt32(Program.actor.birthday.Substring(0, 4));
            }
            placeOfBirth = Program.actor.place_of_birth;
            knownFor = Program.actor.known_for_department;
            if(Program.actor.homepage != null)
                homepage = Program.actor.homepage.ToString();
        }
    }
}

MovieMaven/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieMaven.MovieAPI;
using MovieMaven.Models;

namespace MovieMaven.Pages
{
    public class IndexModel : PageModel
    {
        //public string searchTerm = Temp.searchTerm;
        
        // poster data
        public List<string> posterURLs = new List<string>();
        public List<string> overviews = new List<string>();
        public List<string> movieIDs = new List<string>();

        // video data
        public List<string> videoNames = new List<string>();
        public List<string> videoKeys = new List<string>();
        public int MAX_VIDS = 3; // limits the vids that show
        public int videoRandIndex;

        // movie details
        public string movieOverview;
        public int movieRuntime;
        public string movieTagline;
        public int movieRevenue;
        public string movieReleaseDate;

        // cast details
        public List<string> castPics = new List<string>();
        public List<int> actorIDs = new List<int>();
        public List<string> castNames = new List<string>();

        // inital video 
        public List<string> movieInTheatreURLs = new List<string>();
        public List<string> movieInTheatreIDs = new List<string>();
        public List<Poster> movieInTheatrePosters = new List<Poster>();

        public async Task OnGet()
        {
            // Grab best voting movie by page start up
            await Fetch.GrabPosterAsync("");
            Random randNum = new Random();

            for (int i = 0; i < Program.movieInTheatresSet.results.Count; i++)
            {
                await Fetch.GetMovieDetails(Program.movieInTheatresSet.results[i].id.ToString());
                if (Program.videoSet.results.Count != 0)
                {   // remove poster without video to play
                    movieInTheatrePosters.Add(Program.movieInTheatresSet.results[i]);
                    movieInTheatreURLs.Add(Program.movieInTheatresSet.results[i].poster_path);
                    movieInTheatreIDs.Add(Program.movieInTheatresSet.results[i].id.ToString());
                }
            }
            for (int i = 0; i < 20; i++)
            {
                videoRandIndex = randNum.Next(20);
                await Fetch.GetMovieDetails(Program.movieInTheatresSet.results[videoRandIndex].id.ToString());
                if ((Program.videoSet.results.Count != 0) && (Program.videoSet.results[0].key != null))
                    break;
            }
        }

        public async Task OnPostGetPosters(string search)
        {
            if (Temp.searchTerm != null && search == null)
                search = Temp.searchTerm;

            Temp.searchTerm = search;
            if (search != null) 
            {
                await Fetch.GrabPosterAsync(search);
                foreach (Poster poster in Program.posterSet.results)
                {
                    posterURLs.Add(poster.poster_path);
                    overviews.Add(poster.overview);
                    movieIDs.Add(poster.id.ToString());
                }
            }
        } // OnPostGetPosters()

        public async Task OnPostDetails(string movieID)
        {
            await Fetch.GetMovieDetails(movieID);
            foreach (Video video in Program.videoSet.results)
            {
                videoNames.Add(video.name);
                videoKeys.Add(video.key);
            }
            movieOverview = Program.movie.overview;
            movieRuntime = Program.movie.runtime;
            movieTagline = Program.movie.tagline;
            movieRevenue = Program.movie.revenue;
            movieReleaseDate = Program.movie.release_date;

            for(int i = 0; i < Program.credits.cast.Count; i++)
            {
                castPics.Add(Program.credits.cast[i].profile_path);
                actorIDs.Add(Program.credits.cast[i].id);
                castNames.Add(Program.credits.cast[i].name);
            }

        } // OnPostDetails()

        public void OnPostCastDetails(string actorID)
        {
            Response.Redirect("./Actor?id=" + actorID);
        }

        public async Task OnPostMoviesInTheatresDetails(string movieInTheatreID)
        {
            for (int i = 0; i < Program.movieInTheatresSet.results.Count; i++)
            {
                await Fetch.GetMovieDetails(Program.movieInTheatresSet.results[i].id.ToString());
                if (Program.videoSet.results.Count != 0)
                {   // remove poster without video to play
                    movieInTheatrePosters.Add(Program.movieInTheatresSet.results[i]);
                    movieInTheatreURLs.Add(Program.movieInTheatresSet.results[i].poster_path);
                    movieInTheatreIDs.Add(Program.movieInTheatresSet.results[i].id.ToString());
                }
            }
            await Fetch.GetMovieDetails(movieInTheatreID);
        }
    } // class
} // namespace

MovieMaven/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

MovieMaven/Pages/Actor.cshtml
@page
@model MovieMaven.Pages.ActorModel
@{
    ViewData["Title"] = "Actor";
}

<div id="actorFrame">
    <div id="actorStats" style="background-image: url('../images/bkgCover.png'), url('https://image.tmdb.org/t/p/w500/@Model.imageUrls[0]');"></div>
    <div id="actorBio">
        <h2>@Model.actorName</h2>
        <h3>Biography</h3>
        <p class="bio">@Model.biography</p>
    </div>
</div>

<div id="actorsInfo">
    <h3 style="margin-bottom: 20px; font-weight:bold">Personal Info</h3>
    <h4>Known For: </h4>
    <h5>@Model.knownFor</h5>
    <h4>Gender:</h4>
    @{
        string gender = null;
        if (@Program.actor.gender == 1)
        {
            gender = "Female";
        }
        else
        {
            gender = "Male";
        }
    }
    <h5>@gender</h5>
    <h4>Popularty: </h4>
    <h5>@Program.actor.popularity</h5>
    <h4>Birthday: </h4>
    @if (Program.actor.birthday != null)
    {
        <h5>@Program.actor.birthday</h5>
    }
    else
    {
        <h5>Unknown</h5>
    }
    <h4>Place of Birth:</h4>
    @if (Program.actor.place_of_birth != null)
    {
        <h5>@Program.actor.place_of_birth</h5>
    }
    else
    {
        <h5>Unknown</h5>
    }
    <h4>Age:</h4>
    @if (Model.age != 0)
    {
        <h5>@Model.age</h5>
    }
    else
    {
        <h5>Unknown</h5>
    }

    <h4>Official Site:</h4>
    @if (Model.homepage != null)
    {
        <h5>@Model.homepage</h5>
    }
    else
    {
        <h5>Unknown</h5>
    }
    <h4>Also Know As:</h4>
    @if (Program.actor.also_known_as.Count == 0)
    {
        <h5> Unknown </h5>
    }
    @for (int i = 0; i < Program.actor.also_known_as.Count; i++)
    {
        <h5 style="margin-bottom: 0;">@Program.actor.also_known_as[i]</h5>
    }
</div>

<div id="gallery">
    <h3 style="margin: 20px 0 0 180px; font-weight:bold">Photo Gallery</h3>
    <div id="imageGallery">
        <div class="container-fluid">
            <div class="row">
                <div style="margin-right:0;" class="col-xs-11 col-md-10 col-centered">
                    <div id="carousel" class="carousel slide cars1" data-ride="carousel" data-type="multi" data-interval="2500">
                        <div class="carousel-inner">

                            @for (int i = 0; i < Model.imageUrls.Count; i++)
                            {
                                string active = null;
                                if (i == 0)
                                {
                                    active = "item active";
                                }
                                else
                                {
                                    active = "item";
                                }
                                <div class="@active">
                                    <div class="card pull-left carousel-col">
                                        <img class="img-single card-img-top img-responsive" src="https://image.tmdb.org/t/p/w500/@Program.profileSet.profiles[i].file_path" alt="...">
                                    </div>
                                </div>
                            }
                        </div>
                        <a class="left carousel-control" href="#carousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
                        <a class="right carousel-control" href="#carousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <h3 style="margin: 40px 0 0 180px; font-weight:bold">Profile Set</h3>
    <div id="relatedGallery">
        <div class="container-fluid">
            <div class="row">
                <div style="margin-right:0;" class="col-xs-11 col-md-10 col-centered">
                    <div id="carousel2" class="carousel slide cars2" data-ride="carousel" data-type="multi" data-interval="2500">
                        <div class="carousel-inner">

                            @for (int i = 0; i < Model.movieImages.Count; i++)
                            {
                                string active = null;
                                if (i == 0)
                                {
                                    active = "item active";
                                }
                                else
                                {
                                    active = "item";
                                }
                                @if (Model.movieImages[i] != null)
                                {
                                    <div class="@active">
                                        <div class="card pull-left carousel-col">
                                            <img class="img-single card-img-top img-responsive" src="https://image.tmdb.org/t/p/w500/@Model.movieImages[i]" alt="...">
                                        </div>
                                    </div>
                                }
                            }
                        </div>

                        <a class="left carousel-control" href="#carousel2" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
                        <a class="right carousel-control" href="#carousel2" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

MovieMaven/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MovieMaven/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@if ((Program.videoSet != null) && (Program.videoSet.results.Count != 0))
{
    <div id="searchDiv" class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" style="pointer-events:none" frameborder="0"
                src="https://youtube.com/embed/@Program.videoSet.results[0].key?modestbranding=1&cc_load_policy=1&vq=large&autoplay=1&mute=1&loop=1&playlist=@Program.videoSet.results[0].key&controls=0&autohide=1&rel=0" allowfullscreen>
        </iframe>
    </div>
}
else
{
    <div id="searchDiv" class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" style="pointer-events:none" frameborder="0"
                src="https://youtube.com/embed/szby7ZHLnkA?modestbranding=1&cc_load_policy=1&vq=large&autoplay=1&mute=1&loop=1&playlist=szby7ZHLnkA&controls=0&autohide=1&rel=0" allowfullscreen>
        </iframe>
    </div>
}


<div id="posters">
    @if (Model.movieInTheatreURLs.Count != 0)
    {
        <h3>Popular Movies now playing</h3>
    }
    <form method="post" asp-page-handler="MoviesInTheatresDetails">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @for (int i = 0; i < Model.movieInTheatreURLs.Count; i++)
                    {
                        if (Model.movieInTheatreURLs[i] != null)
                        {
                            <div class="col-sm-3" style="min-width:266px; margin-top: 15px;">
                                <div class="card pull-left">
                                    <div class="card-img-top thumbs" style="float: left;">
                                        <button id="imageButton" style="background: url(https://image.tmdb.org/t/p/w500/@Model.movieInTheatreURLs[i]); background-size: 100%;" type="submit" name="movieInTheatreID" value="@Model.movieInTheatreIDs[i]">
                                            @{ string adult = "";
                                                if (Model.movieInTheatrePosters[i].adult == "false")
                                                { adult = "no"; }
                                                else { adult = "yes"; }
                                            }
                                            <table class="tooltip">
                                                <tr>
                                                    <td>Title</td>
                                                    <td>:&nbsp;@Model.movieInTheatrePosters[i].title</td>
                                                </tr>
                                                <tr>
                                                    <td>Language</td>
                                                    <td>:&nbsp;@Model.movieInTheatrePosters[i].original_language</td>
                                                </tr>
                                                <tr>
                                                    <td>Release date</td>
                                                    <td>:&nbsp;@Model.movieInTheatrePosters[i].release_date</td>
                                                </tr>
                                                <tr>
                                                    <td>Adult</td>
                                                    <td>:&nbsp;@adult</td>
                                                </tr>
                                                <tr>
                                                    <td>Vote average</td>
                                                    <td>:&nbsp;@Model.movieInTheatrePosters[i].vote_average</td>
                                                </tr>
                                                <tr>
                                                    <td>Popularity</td>
                                                    <td>:&nbsp;@Model.movieInTheatrePosters[i].popularity</td>
                                                </tr>
                                            </table>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </form>
</div>

@*
    @if (Model.searchTerm != null)
    {
        <form method="post" asp-page-handler="GetPosters">
            <input type="submit" name="movieID"
                    value="@Model.searchTerm" />
        </form>
    }
*@

<div id="posters">
    <form method="post" asp-page-handler="Details">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @for (int i = 0; i < Model.posterURLs.Count; i++)
                    {
                        string path_backdrop = "https://image.tmdb.org/t/p/w500" +
                        @Program.posterSet.results[i].backdrop_path; // Model.posterURLs[i];
                        string path = "https://image.tmdb.org/t/p/w500" +
                        @Program.posterSet.results[i].poster_path; // Model.posterURLs[i];
                        if (@Program.posterSet.results[i].poster_path != null)
                        {
                            <div class="col-sm-3" style="min-width:266px; margin-top: 15px;">
                                <div class="card pull-left">
                                    <img src="@path" class="card-img-top thumbs" alt="...">
                                    @{ string adult = "";
                                        if (Program.posterSet.results[i].adult == "false")
                                        { adult = "no"; }
                                        else { adult = "yes"; }
                                    }
                                    <table class="tooltip">
                                        <tr>
                                            <td>Title</td>
                                            <td>:&nbsp;@Program.posterSet.results[i].title</td>
                                        </tr>
                                        <tr>
                                            <td>Language</td>
                                            <td>:&nbsp;@Program.posterSet.results[i].original_language</td>
                                        </tr>
                                        <tr>
                                            <td>Release date</td>
                                            <td>:&nbsp;@Program.posterSet.results[i].release_date</td>
                                        </tr>
                                        <tr>
                                            <td>Adult</td>
                                            <td>:&nbsp;@adult</td>
                                        </tr>
                                        <tr>
                                            <td>Vote average</td>
                                            <td>:&nbsp;@Program.posterSet.results[i].vote_average</td>
                                        </tr>
                                        <tr>
                                            <td>Popularity</td>
                                            <td>:&nbsp;@Program.posterSet.results[i].popularity</td>
                                        </tr>
                                    </table>
                                    <div class="card-body">
                                        <p class="card-text movieInfo">
                                            @Model.overviews[i]
                                        </p>
                                    </div>
                                    <div class="card-body">
                                        <button type="submit" name="movieID" class="btn btn-primary" value="@Model.movieIDs[i]">See more...</button>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </form>
</div>

<div id="movieDetails" style="padding: 25px;">
    @if (Model.movieRuntime > 0)
    {
        <div class="alert alert-secondary" role="alert">Runtime: @Model.movieRuntime.ToString() mins</div>
        <div class="alert alert-info" role="heading">Movie Tagline: @Model.movieTagline</div>
        <p>@Model.movieOverview</p>
    }
</div>

<div id="cast" style="text-align: center;">
    <!-- use this for the URL: https://image.tmdb.org/t/p/w500/ -->
    <form method="post" asp-page-handler="CastDetails">
        @if (Model.castPics.Count > 0)
        {
            <h2>Full Cast & Crew</h2>
            @for (int i = 0; i < Model.castPics.Count; i++)
            {
                if (@Model.castPics[i] != null)
                {
                    <div class="castPic"
                         style="background: url(https://image.tmdb.org/t/p/w500/@Model.castPics[i]); background-position: center; background-size: 100%;">
                        <button class="castButton" type="submit" name="actorID" value="@Model.actorIDs[i]">
                            @Model.castNames[i]
                        </button>
                    </div>

                }
            }
        }
    </form>
</div>